-- MySQL Script generated by MySQL Workbench
-- 03/11/17 19:27:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema twt
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema twt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `twt` DEFAULT CHARACTER SET utf8 ;
USE `twt` ;

-- -----------------------------------------------------
-- Table `twt`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `twt`.`user` ;

CREATE TABLE IF NOT EXISTS `twt`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(250) NOT NULL,
  `password` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twt`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `twt`.`role` ;

CREATE TABLE IF NOT EXISTS `twt`.`role` (
  `idrole` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(250) NULL,
  `description` VARCHAR(500) NULL,
  PRIMARY KEY (`idrole`),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twt`.`user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `twt`.`user_role` ;

CREATE TABLE IF NOT EXISTS `twt`.`user_role` (
  `iduser_role` INT NOT NULL AUTO_INCREMENT,
  `user_iduser` INT NOT NULL,
  `role_idrole` INT NOT NULL,
  PRIMARY KEY (`iduser_role`),
  INDEX `fk_user_role_user1_idx` (`user_iduser` ASC),
  INDEX `fk_user_role_role1_idx` (`role_idrole` ASC),
  CONSTRAINT `fk_user_role_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `twt`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_role_role1`
    FOREIGN KEY (`role_idrole`)
    REFERENCES `twt`.`role` (`idrole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twt`.`follow`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `twt`.`follow` ;

CREATE TABLE IF NOT EXISTS `twt`.`follow` (
  `idfollow` INT NOT NULL AUTO_INCREMENT,
  `followed_userid` INT NOT NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`idfollow`),
  INDEX `fk_follow_user_idx` (`user_iduser` ASC),
  CONSTRAINT `fk_follow_user`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `twt`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `twt`.`post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `twt`.`post` ;

CREATE TABLE IF NOT EXISTS `twt`.`post` (
  `idpost` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(250) NULL,
  `content` VARCHAR(250) NULL,
  `user_iduser` INT NULL,
  PRIMARY KEY (`idpost`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twt`.`tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `twt`.`tag` ;

CREATE TABLE IF NOT EXISTS `twt`.`tag` (
  `idtag` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(250) NULL,
  PRIMARY KEY (`idtag`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twt`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `twt`.`comment` ;

CREATE TABLE IF NOT EXISTS `twt`.`comment` (
  `idcomment` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(250) NULL,
  `user_iduser` INT NULL,
  `post_idpost` INT NULL,
  PRIMARY KEY (`idcomment`),
  INDEX `fk_comment_user1_idx` (`user_iduser` ASC),
  INDEX `fk_comment_post1_idx` (`post_idpost` ASC),
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `twt`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_post1`
    FOREIGN KEY (`post_idpost`)
    REFERENCES `twt`.`post` (`idpost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twt`.`tag_relation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `twt`.`tag_relation` ;

CREATE TABLE IF NOT EXISTS `twt`.`tag_relation` (
  `tag_idtag` INT NULL,
  `post_idpost` INT NULL,
  `comment_idcomment` INT NULL,
  `tag_relationcol` VARCHAR(45) NOT NULL,
  INDEX `fk_tag_relation_tag1_idx` (`tag_idtag` ASC),
  INDEX `fk_tag_relation_post1_idx` (`post_idpost` ASC),
  INDEX `fk_tag_relation_comment1_idx` (`comment_idcomment` ASC),
  PRIMARY KEY (`tag_relationcol`),
  CONSTRAINT `fk_tag_relation_tag1`
    FOREIGN KEY (`tag_idtag`)
    REFERENCES `twt`.`tag` (`idtag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tag_relation_post1`
    FOREIGN KEY (`post_idpost`)
    REFERENCES `twt`.`post` (`idpost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tag_relation_comment1`
    FOREIGN KEY (`comment_idcomment`)
    REFERENCES `twt`.`comment` (`idcomment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twt`.`like`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `twt`.`like` ;

CREATE TABLE IF NOT EXISTS `twt`.`like` (
  `idlike` INT NOT NULL AUTO_INCREMENT,
  `comment_idcomment` INT NULL,
  `post_idpost` INT NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`idlike`),
  INDEX `fk_like_comment1_idx` (`comment_idcomment` ASC),
  INDEX `fk_like_post1_idx` (`post_idpost` ASC),
  INDEX `fk_like_user1_idx` (`user_iduser` ASC),
  CONSTRAINT `fk_like_comment1`
    FOREIGN KEY (`comment_idcomment`)
    REFERENCES `twt`.`comment` (`idcomment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_like_post1`
    FOREIGN KEY (`post_idpost`)
    REFERENCES `twt`.`post` (`idpost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_like_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `twt`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
